name: Upload translation file Using Upload API

on:
  # Allows this workflow to be triggered by another workflow
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Action Checkout
        uses: actions/checkout@v3
        
      - name: Generate Timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +%s)" >>$GITHUB_OUTPUT
          echo "WORK_DIR=$GITHUB_WORKSPACE" >>$GITHUB_OUTPUT
          
      - name: Generate DevHash
        id: devhash
        run: |    
          echo -n  ${{ steps.timestamp.outputs.TIMESTAMP }}"i9gc71po2CQSNckiUD44yc9uGzWSGTWO" | md5sum | awk '{print $1}' > hash.txt
          echo "DEVHASH=$(cat hash.txt)" >> $GITHUB_OUTPUT 
        
      - name: Print Variables
        run: |
          echo TIMESTAMP = ${{ steps.timestamp.outputs.TIMESTAMP }}        
          echo DEVHASH = ${{ steps.devhash.outputs.DEVHASH }}
          echo WORK_DIR = ${{ steps.timestamp.outputs.WORK_DIR }}

      - name: List OneSKY Files API
        run: |
          curl "https://platform.api.onesky.io/1/projects/388361/files?api_key=S2RQU74NzKwdNHlxagszjsTPRGyoqk39&timestamp=${{ steps.timestamp.outputs.TIMESTAMP }}&dev_hash=${{ steps.devhash.outputs.DEVHASH }}"


      - name: Trigger Upload API    
        env:
          FILE_PATH: '/src/main/resources/uploadToOneSky/zzz.json'
          FILE_FORMAT: 'HIERARCHICAL_JSON'
          PROJECT_ID : 388361
        run: |
          curl -v -F api_key=S2RQU74NzKwdNHlxagszjsTPRGyoqk39 \
          -F timestamp=${{ steps.timestamp.outputs.TIMESTAMP }} \
          -F dev_hash=${{ steps.devhash.outputs.DEVHASH }} \
          -F "file=@${{ steps.timestamp.outputs.WORK_DIR }}${{ env.FILE_PATH }}" \
          -F file_format=${{ env.FILE_FORMAT }}  \
          "https://platform.api.onesky.io/1/projects/${{ env.PROJECT_ID }}/files"
    
