name: Upload translation file Using Upload API

on:
  schedule:
  - cron: '* * * * 4' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +%s)" >>$GITHUB_OUTPUT
          
      - name: Generate DevHash
        id: devhash
        run: |    
          echo -n  ${{ steps.timestamp.outputs.TIMESTAMP }}"i9gc71po2CQSNckiUD44yc9uGzWSGTWO" | md5sum | awk '{print $1}' > hash.txt
          echo "DEVHASH=$(cat hash.txt)" >> $GITHUB_OUTPUT 
        
        
#          echo "DEVHASH=$(echo -n ${{ steps.timestamp.outputs.TIMESTAMP }}'i9gc71po2CQSNckiUD44yc9uGzWSGTWO' | md5sum | awk '{print $1}' )" >> $GITHUB_OUTPUT
#          echo ${{ steps.timestamp.outputs.TIMESTAMP }}
#          echo ${{ steps.devhash.outputs.DEVHASH }}
          
#          echo -n ${{ steps.timestamp.outputs.TIMESTAMP }}'i9gc71po2CQSNckiUD44yc9uGzWSGTWO' | md5sum 
#          echo "DEVHASH=$( echo -n  ${{ steps.timestamp.outputs.TIMESTAMP }}'i9gc71po2CQSNckiUD44yc9uGzWSGTWO' | md5sum )" >>$GITHUB_OUTPUT
      - name: Print Variables
        run: |
          echo TIMESTAMP = ${{ steps.timestamp.outputs.TIMESTAMP }}        
          echo DEVHASH = ${{ steps.devhash.outputs.DEVHASH }}

      - name: List OneSKY Files API
        run: |
          curl https://platform.api.onesky.io/1/projects/388361/files?api_key=S2RQU74NzKwdNHlxagszjsTPRGyoqk39&timestamp=${{ steps.timestamp.outputs.TIMESTAMP }}&dev_hash=${{ steps.devhash.outputs.DEVHASH }}


      - name: Trigger Upload API    
        env:
          FILE_PATH: 'src/main/resources/uploadToOneSky/zzz.json'
          FILE_FORMAT: 'HIERARCHICAL_JSON'
          PROJECT_ID : 388361
        run: |
          curl -X POST https://platform.api.onesky.io/1/projects/${{ env.PROJECT_ID }}/files \
          -H 'Content-Type: multipart/form-data' \
          -d '{"api_key": "S2RQU74NzKwdNHlxagszjsTPRGyoqk39", "timestamp": "${{ steps.timestamp.outputs.TIMESTAMP }}", \ 
          "dev_hash": "${{ steps.devhash.outputs.DEVHASH }}", "file": "@${{ env.FILE_PATH }}", "file_format": "${{ env.FILE_FORMAT }}" }'    


#          curl -X POST https://platform.api.onesky.io/1/projects/${{ env.PROJECT_ID }}/files \
#          -H 'Content-Type: multipart/form-data' \
#          -d '{"api_key": "S2RQU74NzKwdNHlxagszjsTPRGyoqk39", "timestamp": ${{ steps.timestamp.outputs.TIMESTAMP }}, \ 
#          "dev_hash": ${{ steps.devhash.outputs.DEVHASH }}, "file": "${{ env.FILE_PATH }}", "file_format": ${{ env.FILE_FORMAT }} }'       

